"use strict";

// Les 48 sélections FIFA 2026, plus le Cambodge en équipe bonus.
// Chaque mini-équipe réunit quatre internationaux contemporains : GK, DF, MF et FW.
window.BWC_TEAM_DATA={
countries:{
"Algérie":["🇩🇿","#f5f5f5","#16804a","#f5f5f5","#d71920"],
"Argentine":["🇦🇷","#75aadb","#18233f","#fff","#fff"],
"Australie":["🇦🇺","#ffcd00","#087a43","#ffcd00","#17683a"],
"Autriche":["🇦🇹","#d81e2b","#fff","#d81e2b","#fff"],
"Belgique":["🇧🇪","#e30613","#111","#e30613","#f0cb24"],
"Bosnie-Herzégovine":["🇧🇦","#174a9c","#ffdf00","#174a9c","#fff"],
"Brésil":["🇧🇷","#ffcc00","#2146a8","#fff","#16834b"],
"Cambodge":["🇰🇭","#1642a3","#d72632","#1642a3","#fff"],
"Cap-Vert":["🇨🇻","#174ea6","#fff","#d82c3a","#f6cf3d"],
"Canada":["🇨🇦","#e01d2f","#fff","#e01d2f","#fff"],
"Colombie":["🇨🇴","#fcd116","#173b8e","#ce1126","#ce1126"],
"RD Congo":["🇨🇩","#1983d7","#f7d618","#1983d7","#e62d3e"],
"Côte d'Ivoire":["🇨🇮","#f77f00","#fff","#f77f00","#16834b"],
"Croatie":["🇭🇷","#f3f3f3","#1b45a0","#fff","#e1262f"],
"Curaçao":["🇨🇼","#1450a3","#f4d21f","#1450a3","#fff"],
"Tchéquie":["🇨🇿","#d7141a","#11457e","#fff","#fff"],
"Équateur":["🇪🇨","#ffdd00","#18355b","#aa1725","#17388c"],
"Égypte":["🇪🇬","#ce1126","#fff","#111","#fff"],
"Angleterre":["🏴","#f4f4f4","#142653","#f4f4f4","#d71920"],
"France":["🇫🇷","#1746b4","#fff","#dc2435","#fff"],
"Allemagne":["🇩🇪","#f4f4f4","#151515","#f4f4f4","#d8bd27"],
"Ghana":["🇬🇭","#f3f3f3","#111","#f3f3f3","#cf2732"],
"Haïti":["🇭🇹","#1943a2","#d42b39","#1943a2","#fff"],
"Iran":["🇮🇷","#fff","#16804a","#d72534","#fff"],
"Irak":["🇮🇶","#17823b","#fff","#17823b","#d71920"],
"Japon":["🇯🇵","#172e8b","#fff","#172e8b","#d12536"],
"Jordanie":["🇯🇴","#fff","#d71920","#fff","#16804a"],
"Corée du Sud":["🇰🇷","#e82432","#172653","#e82432","#fff"],
"Mexique":["🇲🇽","#087347","#fff","#c72936","#fff"],
"Maroc":["🇲🇦","#c1272d","#1a713f","#c1272d","#fff"],
"Pays-Bas":["🇳🇱","#f36c21","#192d5e","#f36c21","#fff"],
"Nouvelle-Zélande":["🇳🇿","#151515","#fff","#151515","#fff"],
"Norvège":["🇳🇴","#ba1838","#172b5d","#ba1838","#fff"],
"Panama":["🇵🇦","#d51933","#153b87","#fff","#fff"],
"Paraguay":["🇵🇾","#d52b3f","#1f3b7d","#fff","#fff"],
"Portugal":["🇵🇹","#d51e2f","#12633c","#d51e2f","#e8c749"],
"Qatar":["🇶🇦","#8a1538","#fff","#8a1538","#fff"],
"Arabie saoudite":["🇸🇦","#16834b","#fff","#16834b","#fff"],
"Écosse":["🏴","#172a6a","#fff","#172a6a","#fff"],
"Sénégal":["🇸🇳","#fff","#198a4a","#fff","#f5d328"],
"Afrique du Sud":["🇿🇦","#087a4d","#ffbd25","#087a4d","#fff"],
"Espagne":["🇪🇸","#c60b1e","#15204d","#c60b1e","#f2cc35"],
"Suède":["🇸🇪","#fecc00","#185399","#fecc00","#185399"],
"Suisse":["🇨🇭","#d52b1e","#fff","#d52b1e","#fff"],
"Tunisie":["🇹🇳","#e70013","#fff","#e70013","#fff"],
"Turquie":["🇹🇷","#e30a17","#fff","#e30a17","#fff"],
"Uruguay":["🇺🇾","#67a9dd","#111","#67a9dd","#fff"],
"États-Unis":["🇺🇸","#f4f4f4","#17243d","#f4f4f4","#d42236"],
"Ouzbékistan":["🇺🇿","#1687ce","#fff","#1687ce","#1b9855"]
},
countryCodes:{
"Algérie":"dz","Argentine":"ar","Australie":"au","Autriche":"at","Belgique":"be","Bosnie-Herzégovine":"ba","Brésil":"br","Cambodge":"kh","Cap-Vert":"cv","Canada":"ca","Colombie":"co","RD Congo":"cd","Côte d'Ivoire":"ci","Croatie":"hr","Curaçao":"cw","Tchéquie":"cz","Équateur":"ec","Égypte":"eg","Angleterre":"gb-eng","France":"fr","Allemagne":"de","Ghana":"gh","Haïti":"ht","Iran":"ir","Irak":"iq","Japon":"jp","Jordanie":"jo","Corée du Sud":"kr","Mexique":"mx","Maroc":"ma","Pays-Bas":"nl","Nouvelle-Zélande":"nz","Norvège":"no","Panama":"pa","Paraguay":"py","Portugal":"pt","Qatar":"qa","Arabie saoudite":"sa","Écosse":"gb-sct","Sénégal":"sn","Afrique du Sud":"za","Espagne":"es","Suède":"se","Suisse":"ch","Tunisie":"tn","Turquie":"tr","Uruguay":"uy","États-Unis":"us","Ouzbékistan":"uz"
},
countryEnglish:{
"Algérie":"Algeria","Argentine":"Argentina","Australie":"Australia","Autriche":"Austria","Belgique":"Belgium","Bosnie-Herzégovine":"Bosnia and Herzegovina","Brésil":"Brazil","Cambodge":"Cambodia","Cap-Vert":"Cape Verde","Canada":"Canada","Colombie":"Colombia","RD Congo":"DR Congo","Côte d'Ivoire":"Ivory Coast","Croatie":"Croatia","Curaçao":"Curaçao","Tchéquie":"Czechia","Équateur":"Ecuador","Égypte":"Egypt","Angleterre":"England","France":"France","Allemagne":"Germany","Ghana":"Ghana","Haïti":"Haiti","Iran":"Iran","Irak":"Iraq","Japon":"Japan","Jordanie":"Jordan","Corée du Sud":"South Korea","Mexique":"Mexico","Maroc":"Morocco","Pays-Bas":"Netherlands","Nouvelle-Zélande":"New Zealand","Norvège":"Norway","Panama":"Panama","Paraguay":"Paraguay","Portugal":"Portugal","Qatar":"Qatar","Arabie saoudite":"Saudi Arabia","Écosse":"Scotland","Sénégal":"Senegal","Afrique du Sud":"South Africa","Espagne":"Spain","Suède":"Sweden","Suisse":"Switzerland","Tunisie":"Tunisia","Turquie":"Türkiye","Uruguay":"Uruguay","États-Unis":"United States","Ouzbékistan":"Uzbekistan"
},
nationalPlayers:{
"Algérie":{GK:"Luca Zidane",DF:"Aïssa Mandi",MF:"Nabil Bentaleb",FW:"Riyad Mahrez"},
"Argentine":{GK:"Emiliano Martínez",DF:"Nicolás Otamendi",MF:"Rodrigo De Paul",FW:"Lionel Messi"},
"Australie":{GK:"Mathew Ryan",DF:"Aziz Behich",MF:"Jackson Irvine",FW:"Mathew Leckie"},
"Autriche":{GK:"Alexander Schlager",DF:"David Alaba",MF:"Marcel Sabitzer",FW:"Marko Arnautović"},
"Belgique":{GK:"Thibaut Courtois",DF:"Thomas Meunier",MF:"Axel Witsel",FW:"Romelu Lukaku"},
"Bosnie-Herzégovine":{GK:"Nikola Vasilj",DF:"Sead Kolašinac",MF:"Amir Hadžiahmetović",FW:"Edin Džeko"},
"Brésil":{GK:"Alisson",DF:"Marquinhos",MF:"Casemiro",FW:"Neymar Jr"},
"Cambodge":{GK:"Keo Soksela",DF:"Takaki Ose",MF:"Yudai Ogawa",FW:"Sieng Chanthea"},
"Cap-Vert":{GK:"Vozinha",DF:"Stopira",MF:"Garry Rodrigues",FW:"Ryan Mendes"},
"Canada":{GK:"Maxime Crépeau",DF:"Richie Laryea",MF:"Jonathan Osorio",FW:"Jonathan David"},
"Colombie":{GK:"David Ospina",DF:"Davinson Sánchez",MF:"James Rodríguez",FW:"Luis Díaz"},
"RD Congo":{GK:"Lionel Mpasi",DF:"Chancel Mbemba",MF:"Samuel Moutoussamy",FW:"Cédric Bakambu"},
"Côte d'Ivoire":{GK:"Yahia Fofana",DF:"Ghislain Konan",MF:"Franck Kessié",FW:"Nicolas Pépé"},
"Croatie":{GK:"Dominik Livaković",DF:"Joško Gvardiol",MF:"Luka Modrić",FW:"Ivan Perišić"},
"Curaçao":{GK:"Eloy Room",DF:"Jurien Gaari",MF:"Leandro Bacuna",FW:"Gervane Kastaneer"},
"Tchéquie":{GK:"Matěj Kovář",DF:"Vladimír Coufal",MF:"Tomáš Souček",FW:"Patrik Schick"},
"Équateur":{GK:"Hernán Galíndez",DF:"Ángelo Preciado",MF:"Moisés Caicedo",FW:"Enner Valencia"},
"Égypte":{GK:"Mohamed El Shenawy",DF:"Ramy Rabia",MF:"Hamdy Fathy",FW:"Mohamed Salah"},
"Angleterre":{GK:"Jordan Pickford",DF:"John Stones",MF:"Jordan Henderson",FW:"Harry Kane"},
"France":{GK:"Mike Maignan",DF:"Lucas Digne",MF:"N’Golo Kanté",FW:"Kylian Mbappé"},
"Allemagne":{GK:"Manuel Neuer",DF:"Joshua Kimmich",MF:"Leroy Sané",FW:"Kai Havertz"},
"Ghana":{GK:"Lawrence Ati-Zigi",DF:"Baba Rahman",MF:"Thomas Partey",FW:"Jordan Ayew"},
"Haïti":{GK:"Johny Placide",DF:"Ricardo Adé",MF:"Danley Jean Jacques",FW:"Duckens Nazon"},
"Iran":{GK:"Alireza Beiranvand",DF:"Ehsan Hajsafi",MF:"Alireza Jahanbakhsh",FW:"Mehdi Taremi"},
"Irak":{GK:"Jalal Hassan",DF:"Rebin Sulaka",MF:"Ibrahim Bayesh",FW:"Aymen Hussein"},
"Japon":{GK:"Zion Suzuki",DF:"Yuto Nagatomo",MF:"Junya Ito",FW:"Ayase Ueda"},
"Jordanie":{GK:"Yazeed Abulaila",DF:"Ehsan Haddad",MF:"Rajaei Ayed",FW:"Ali Olwan"},
"Corée du Sud":{GK:"Kim Seung-gyu",DF:"Kim Min-jae",MF:"Lee Jae-sung",FW:"Son Heung-min"},
"Mexique":{GK:"Guillermo Ochoa",DF:"Jesús Gallardo",MF:"Orbelín Pineda",FW:"Raúl Jiménez"},
"Maroc":{GK:"Yassine Bounou",DF:"Achraf Hakimi",MF:"Sofyan Amrabat",FW:"Ayoub El Kaabi"},
"Pays-Bas":{GK:"Bart Verbruggen",DF:"Virgil van Dijk",MF:"Frenkie de Jong",FW:"Memphis Depay"},
"Nouvelle-Zélande":{GK:"Max Crocombe",DF:"Michael Boxall",MF:"Elijah Just",FW:"Chris Wood"},
"Norvège":{GK:"Ørjan Nyland",DF:"Kristoffer Ajer",MF:"Martin Ødegaard",FW:"Erling Haaland"},
"Panama":{GK:"Luis Mejía",DF:"Eric Davis",MF:"Aníbal Godoy",FW:"José Fajardo"},
"Paraguay":{GK:"Gatito Fernández",DF:"Gustavo Gómez",MF:"Miguel Almirón",FW:"Antonio Sanabria"},
"Portugal":{GK:"Diogo Costa",DF:"Rúben Dias",MF:"Bernardo Silva",FW:"Cristiano Ronaldo"},
"Qatar":{GK:"Meshaal Barsham",DF:"Boualem Khoukhi",MF:"Abdulaziz Hatem",FW:"Almoez Ali"},
"Arabie saoudite":{GK:"Mohammed Alowais",DF:"Saud Abdulhamid",MF:"Mohamed Kanno",FW:"Salem Aldawsari"},
"Écosse":{GK:"Craig Gordon",DF:"Andy Robertson",MF:"John McGinn",FW:"Che Adams"},
"Sénégal":{GK:"Édouard Mendy",DF:"Kalidou Koulibaly",MF:"Idrissa Gana Gueye",FW:"Sadio Mané"},
"Afrique du Sud":{GK:"Ronwen Williams",DF:"Aubrey Modiba",MF:"Teboho Mokoena",FW:"Lyle Foster"},
"Espagne":{GK:"Unai Simón",DF:"Aymeric Laporte",MF:"Rodri",FW:"Mikel Oyarzabal"},
"Suède":{GK:"Kristoffer Nordfeldt",DF:"Victor Lindelöf",MF:"Mattias Svanberg",FW:"Viktor Gyökeres"},
"Suisse":{GK:"Gregor Kobel",DF:"Ricardo Rodríguez",MF:"Granit Xhaka",FW:"Breel Embolo"},
"Tunisie":{GK:"Aymen Dahmen",DF:"Montassar Talbi",MF:"Ellyes Skhiri",FW:"Firas Chaouat"},
"Turquie":{GK:"Uğurcan Çakır",DF:"Merih Demiral",MF:"Hakan Çalhanoğlu",FW:"Kerem Aktürkoğlu"},
"Uruguay":{GK:"Fernando Muslera",DF:"José María Giménez",MF:"Federico Valverde",FW:"Darwin Núñez"},
"États-Unis":{GK:"Matt Turner",DF:"Tim Ream",MF:"Weston McKennie",FW:"Christian Pulisic"},
"Ouzbékistan":{GK:"Utkir Yusupov",DF:"Farrukh Sayfiev",MF:"Otabek Shukurov",FW:"Eldor Shomurodov"}
}
};
